name: build-wayblue
on:
  schedule:
    - cron: "00 5 * * *" # build at 5:00 UTC every day 
    
  push:
    branches-ignore: # don't rebuild for dependabot
      - 'dependabot/**'
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
      
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build wayblue
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          - recipe-sway.yml
          - recipe-sway-nvidia.yml
          - recipe-sway-nvidia-open.yml
          - recipe-hyprland.yml
          - recipe-hyprland-nvidia.yml
          - recipe-hyprland-nvidia-open.yml
          - recipe-river.yml
          - recipe-river-nvidia.yml
          - recipe-river-nvidia-open.yml
          - recipe-wayfire.yml
          - recipe-wayfire-nvidia.yml
          - recipe-wayfire-nvidia-open.yml
          - recipe-qtile.yml
          - recipe-qtile-nvidia.yml
          - recipe-qtile-nvidia-open.yml
          - recipe-sway-gdm.yml
          - recipe-sway-nvidia-gdm.yml
          - recipe-sway-nvidia-open-gdm.yml
          - recipe-hyprland-gdm.yml
          - recipe-hyprland-nvidia-gdm.yml
          - recipe-hyprland-nvidia-open-gdm.yml
          - recipe-river-gdm.yml
          - recipe-river-nvidia-gdm.yml
          - recipe-river-nvidia-open-gdm.yml
          - recipe-wayfire-gdm.yml
          - recipe-wayfire-nvidia-gdm.yml
          - recipe-wayfire-nvidia-open-gdm.yml
          - recipe-qtile-gdm.yml
          - recipe-qtile-nvidia-gdm.yml
          - recipe-qtile-nvidia-open-gdm.yml
    steps:
      - name: Optimize build times
        shell: bash
        run: |
          echo 'set man-db/auto-update false' | sudo debconf-communicate
          sudo dpkg-reconfigure man-db
          sudo rm -f /var/lib/man-db/auto-update
          sudo sed -i 's/^update_initramfs=.*/update_initramfs=no/' /etc/initramfs-tools/update-initramfs.conf

      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Gather image data from recipe
        run: |
          echo "IMAGE_NAME=$(grep '^name:' ./recipes/${{ matrix.recipe }} | sed 's/^name: //')" >> $GITHUB_ENV
          echo "IMAGE_MAJOR_VERSION=$(grep '^image-version:' ./recipes/${{ matrix.recipe }} | sed 's/^image-version: //')" >> $GITHUB_ENV
          BASE_IMAGE=$(grep '^base-image:' ./recipes/${{ matrix.recipe }} | sed 's/^base-image: //')
          echo "BASE_IMAGE_NAME=$(echo $BASE_IMAGE | sed 's/.*\/.*\///')" >> $GITHUB_ENV

      - name: Verify base image
        uses: EyeCantCU/cosign-action/verify@58722a084c82190b57863002d494c91eabbe9e79 # v0.3.0
        with:
          containers: ${{ env.BASE_IMAGE_NAME }}:${{ env.IMAGE_MAJOR_VERSION }}
          registry: 'quay.io/fedora-ostree-desktops'
          pubkey: 'https://gitlab.com/fedora/ostree/ci-test/-/raw/main/quay.io-fedora-ostree-desktops.pub'

      - name: Build wayblue
        uses: blue-build/github-action@3cd0c2835e691b87a7eb19261a6aee77a56169e2 # v1.11.0
        with:
          cli_version: v0.9.28
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          build_chunked_oci: true
          max_layers: 128
          maximize_build_space: true
          squash: true
          skip_checkout: true
          use_cache: false
          retry_push_count: 3
          verify_install: true
